### ISSUE TITLE
'tqdm.autonotebook' doesn't exist in older versions

### ISSUE THREAD

**Issue by CorentinJ** [timsainb/noisereduce#10]
With tqdm 4.11.2, the import of noisereduce.py failed due to `tqdm.autonotebook` being missing. I fixed it by updating to 4.31.1. A minimum version should be specified in the requirements.

**Comment by timsainb** [comment]
Thanks, I will fix this in the next update by importing tqdm or autonotebook based on tqdm version in the next update.
