### ISSUE TITLE
remove signal A from signal B

### ISSUE THREAD

**Issue by jeromew** [timsainb/noisereduce#106]
Hello,

can this library be used to remove a signal A that is present in another signal B, but slightly noisy ?

I thought that by using y_noise = signal A it would remove it from signal B as we know exactly the "noise" that we want to remove but this does not seem to work.

I also tried to correlate the 2 signals, and use noisereduce with 2 signal of approximately the same size that contain approximately the same audio, but it did not remove the audio from the signal when I used y = signal A, y_noise = signal B

can you help me understand what y_noise does and how I could achieve cancellation of a noisy copy of a signal ?

thank you for your help

**Comment by timsainb** [comment]
noisereduce works through a spectral gate, so noise reduction is done by separating spectral components of the signal into signal and noise based on some summary statistics. y_noise is used to compute those summary statistics. 

https://en.wikipedia.org/wiki/Noise_gate

We are writing a paper now on this algorithm that will have more details. For now see
- https://www.frontiersin.org/articles/10.3389/fnbeh.2021.811737/full
- https://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1008228

which both summarize the algorithm
