### ISSUE TITLE
install problem with llvmlite dependency

### ISSUE THREAD

**Issue by DaFrenchFrog** [timsainb/noisereduce#108]
I am trying to install noisereduce on a raspberry Pi zero W and with `npm install noisereduce` I get this error :

`Installing collected packages: llvmlite
    Running setup.py install for llvmlite ... error
    ERROR: Command errored out with exit status 1:
     command: /home/romaing/env/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-4e6q9sl6/llvmlite_94b7981d3c4b45a9a24c3fdd7c8cba5f/setup.py'"'"'; __file__='"'"'/tmp/pip-install-4e6q9sl6/llvmlite_94b7981d3c4b45a9a24c3fdd7c8cba5f/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-ofscklt1/install-record.txt --single-version-externally-managed --compile --install-headers /home/romaing/env/include/site/python3.9/llvmlite
         cwd: /tmp/pip-install-4e6q9sl6/llvmlite_94b7981d3c4b45a9a24c3fdd7c8cba5f/
    Complete output (14 lines):
    running install
    running build
    got version from file /tmp/pip-install-4e6q9sl6/llvmlite_94b7981d3c4b45a9a24c3fdd7c8cba5f/llvmlite/_version.py {'version': '0.42.0', 'full': 'b2a26aafd266b8972ad26dfa98dc41642f84913e'}
    running build_ext
    /home/romaing/env/bin/python /tmp/pip-install-4e6q9sl6/llvmlite_94b7981d3c4b45a9a24c3fdd7c8cba5f/ffi/build.py
    LLVM version... Traceback (most recent call last):
      File "/tmp/pip-install-4e6q9sl6/llvmlite_94b7981d3c4b45a9a24c3fdd7c8cba5f/ffi/build.py", line 228, in <module>
        main()
      File "/tmp/pip-install-4e6q9sl6/llvmlite_94b7981d3c4b45a9a24c3fdd7c8cba5f/ffi/build.py", line 218, in main
        main_posix('linux', '.so')
      File "/tmp/pip-install-4e6q9sl6/llvmlite_94b7981d3c4b45a9a24c3fdd7c8cba5f/ffi/build.py", line 135, in main_posix
        raise RuntimeError(msg) from None
    RuntimeError: Could not find a `llvm-config` binary. There are a number of reasons this could occur, please see: https://llvmlite.readthedocs.io/en/latest/admin-guide/install.html#using-pip for help.
    error: command '/home/romaing/env/bin/python' failed with exit code 1`

So the[ llvmlite website states](https://llvmlite.readthedocs.io/en/latest/admin-guide/install.html) the raspberry Pi is not supported.  Does this mean I can't use this great tool on my Rpi or is there a workaround ?

Thx!

**Comment by nuniz** [comment]
Hi,
Noise-reduce doesn't directly require llvmlite. Instead, you're getting this error because of librosa dependency, which require numba. Some functions we used, such as amp_to_db, rely on librosa, so removing this dependency could be helpful in the future @timsainb .

Right now, the dependencies are:
librosa 0.10.2
numba 0.51.0
llvmlite >=0.43

Here are some solutions to try:

1. Install llvmlite directly with conda, if you have that available. See [llvm installation](https://llvmlite.readthedocs.io/en/latest/admin-guide/install.html#compiling-llvm), [numba installation](https://groups.google.com/a/continuum.io/g/numba-users/c/mXpks0pAjg8/m/PmTVdRa6CQAJ?pli=1).
2. https://github.com/numba/llvmlite/issues/604#issuecomment-683424357.

Workarounds:
3. Try installing librosa without dependencies (--no-deps), I'm not sure that this would work, but worth a try.
4. Use [torchgating ](https://github.com/noisereduce/TorchSpectralGating)(the repository that torch noisereduce was first implemented. Note that it does not include audio chunking).

**Comment by DaFrenchFrog** [comment]
Thx for your quick reply.

> Hi, Noise-reduce doesn't directly require llvmlite. Instead, you're getting this error because of librosa dependency, which require numba. Some functions we used, such as amp_to_db, rely on librosa, so removing this dependency could be helpful in the future @timsainb .
> 
> Right now, the dependencies are: librosa 0.10.2 numba 0.51.0 llvmlite >=0.43
> 
> Here are some solutions to try:
> 
> 1. Install llvmlite directly with conda. See [llvm installation](https://llvmlite.readthedocs.io/en/latest/admin-guide/install.html#compiling-llvm), [numba installation](https://groups.google.com/a/continuum.io/g/numba-users/c/mXpks0pAjg8/m/PmTVdRa6CQAJ?pli=1).

> 2. [I can't install llvmlite on raspberry pi 4 numba/llvmlite#604 (comment)](https://github.com/numba/llvmlite/issues/604#issuecomment-683424357).

Thx for your quick reply. From what I understand after reading the llvm ticket stating [here](https://github.com/numba/llvmlite/issues/604#issuecomment-1515600897) it is not possible to install llvm on a raspberry Pi zero W as it is an ARM 32-bit instruction set.

> 
> Workarounds: 3. Try installing librosa without dependencies (--no-deps), I'm not sure that this would work, but worth a try. 4. Use [torchgating ](https://github.com/noisereduce/TorchSpectralGating)(the repository that torch noisereduce was first implemented. Note that it does not include audio chunking).


About your 4. I'm not sure I need audio chuncking. I have wavefiles in which I want to reduce noise. noisereduce was working perfectly running from my server but now I need to use it on my Rpi zero...

**Comment by nuniz** [comment]
Hi,
I've made a new [branch](https://github.com/timsainb/noisereduce/tree/remove-librosa) where I removed the librosa dependency.
See if this works for you.

**Comment by DaFrenchFrog** [comment]
Wow thanks a lot ! So I installed the branch with `pip install git+https://github.com/timsainb/noisereduce.git@remove-librosa` and it worked. 

Then I had [this issue] with scipy (https://stackoverflow.com/questions/14570011/explain-why-numpy-should-not-be-imported-from-source-directory) solved by `sudo apt-get install libopenblas-dev`.

Now I can launch noise reduce without problem but the sound is totally silent. And if the sound is too long (like 10 to 15 seconds) I get this error (I guess the Rpi Pi zero W has its limits) :

```
File "/home/romaing/env/lib/python3.9/site-packages/noisereduce/noisereduce.py", line 185, in reduce_noise
    return sg.get_traces()
  File "/home/romaing/env/lib/python3.9/site-packages/noisereduce/spectralgate/base.py", line 222, in get_traces
    filtered_chunk = self.filter_chunk(start_frame=0, end_frame=end_frame)
  File "/home/romaing/env/lib/python3.9/site-packages/noisereduce/spectralgate/base.py", line 149, in filter_chunk
    filtered_padded_chunk = self._do_filter(padded_chunk)
  File "/home/romaing/env/lib/python3.9/site-packages/noisereduce/spectralgate/nonstationary.py", line 100, in _do_filter
    chunk_filtered = self.spectral_gating_nonstationary(chunk)
  File "/home/romaing/env/lib/python3.9/site-packages/noisereduce/spectralgate/nonstationary.py", line 51, in spectral_gating_nonstationary
    _, _, sig_stft = stft(
  File "/home/romaing/env/lib/python3.9/site-packages/scipy/signal/_spectral_py.py", line 1240, in stft
    freqs, time, Zxx = _spectral_helper(x, x, fs, window, nperseg, noverlap,
  File "/home/romaing/env/lib/python3.9/site-packages/scipy/signal/_spectral_py.py", line 1928, in _spectral_helper
    result = _fft_helper(x, win, detrend_func, nperseg, noverlap, nfft, sides)
  File "/home/romaing/env/lib/python3.9/site-packages/scipy/signal/_spectral_py.py", line 1995, in _fft_helper
    result = np.lib.stride_tricks.sliding_window_view(
  File "/home/romaing/env/lib/python3.9/site-packages/numpy/lib/stride_tricks.py", line 336, in sliding_window_view
    return as_strided(x, strides=out_strides, shape=out_shape,
  File "/home/romaing/env/lib/python3.9/site-packages/numpy/lib/stride_tricks.py", line 105, in as_strided
    array = np.asarray(DummyArray(interface, base=x))
ValueError: array is too big; `arr.size * arr.dtype.itemsize` is larger than the maximum possible size.
```
Do you think there is a solution ?

**Comment by DaFrenchFrog** [comment]
Amazing ! Thx a lot for such a great package & update !

**Comment by nuniz** [comment]
Glad I could help. Good luck with your project :-). I'll leave this issue open for future reference.
