### ISSUE TITLE
Reduce noise in stereo

### ISSUE THREAD

**Issue by olawalejuwonm** [timsainb/noisereduce#114]
Hi.

Thanks for the awesome project.

The output of the sound is in mono (one channel), can there be option to set this or default it to multiple channel?

**Comment by nuniz** [comment]
The input to noisereduce is a 2-dimensional matrix, so you can input stereo into the algorithm and obtain stereo output. However, the noise estimation is not shared between the channels.

**Comment by olawalejuwonm** [comment]
How do I achieve that programmatically?

**Comment by nuniz** [comment]
Take a look at the last part (Multichannel noise) of the example notebook - 
https://github.com/timsainb/noisereduce/blob/master/notebooks/1.0-test-noise-reduction.ipynb

**Comment by olawalejuwonm** [comment]
Thanks for the tip!

But will the output audio file be stereo as well?

**Comment by nuniz** [comment]
Yes. The output shape should be identical to the input shape.

**Comment by olawalejuwonm** [comment]
Ok, thanks.

I noticed this in the codebase:

audio_clip_cafe_2_channel = np.vstack([audio_clip_cafe, audio_clip_cafe])

reduced_noise = nr.reduce_noise(y = audio_clip_cafe_2_channel,
sr=rate, n_std_thresh_stationary=1.5,stationary=True)


Do I need to pass the audio to numpy first before using reduced_noise?

**Comment by nuniz** [comment]
You can use either numpy or torch.

The simplest usage is:
```
import soundfile as sf
import noisereduce as nr

# READ AUDIO
data, sr= sf.read("<PATH_TO_AUDIO>")

# REDUCE NOISE
output = nr.reduce_noise(y = data, sr=sr)

# WRITE AUDIO
sf.write("<PATH_TO_AUDIO>", output , sr)

```

**Comment by olawalejuwonm** [comment]
What will be the value of

audio_clip_cafe_2_channel ?

**Comment by nuniz** [comment]
The audio data

**Comment by olawalejuwonm** [comment]
I don't get.

Can you 🙏 please share the full code?

**Comment by nuniz** [comment]
You can use the code I've written to use noisereduce on stereo-data.

https://github.com/timsainb/noisereduce/issues/114#issuecomment-2407935887
