### ISSUE TITLE
Frames are being removed

### ISSUE THREAD

**Issue by SkyJuniour** [timsainb/noisereduce#12]
I would like to congratulate on your great work, the library works as promised.
But there is a small issue which i found.
When i load the file with librosa.load and give that array as a input to reduce_noise, length of the array gets changed, what is the reason behind this. For a certain project of mine i am trying to use this library on small clips hardly of 1secs, but if such frames keep on vanishing i will loose a lot of important data. What is the workaround for this, moreover why are no of frames getting reduced?

![Capture](https://user-images.githubusercontent.com/51473420/59086795-694b1d80-8920-11e9-8d4c-78f5967fab6f.PNG)

**Comment by timsainb** [comment]
Thanks for raising this issue. Most likely this is due to some clipping (or lack of padding) when making the spectrogram.

**Comment by SkyJuniour** [comment]
Yes i guessed that, but do we have any solution for the same ?

**Comment by timsainb** [comment]
You should be able to pad based upon the fft window length/ hop length. I probably wouldn't be able to get to this myself for a while so if you make this fix, just add a flag for padding and make a pull-request and we can add it in.

**Comment by timsainb** [comment]
The fix for this in librosa is in this thread. I'm going to take care of it.

https://github.com/librosa/librosa/issues/328

**Comment by timsainb** [comment]
See the fix at https://github.com/timsainb/noisereduce/commit/f1cca2225db3f5918c222d018a11379e89f6da6f

**Comment by timsainb** [comment]
@SkyJuniour please make sure the new code works for you and close the issue if so
