### ISSUE TITLE
GPU based error / 

### ISSUE THREAD

**Issue by Tortoise17** [timsainb/noisereduce#15]
HI. Now it seems that new module is only GPU based??? 
or I am making any mistake?? It is giving this with only CPU based machine. 
Please see error.. and help

----> 1 import noisereduce as nr

~/anaconda3/envs/server/lib/python3.6/site-packages/noisereduce/__init__.py in <module>
----> 1 from noisereduce.noisereduce import reduce_noise

~/anaconda3/envs/server/lib/python3.6/site-packages/noisereduce/noisereduce.py in <module>
     10 
     11     print(
---> 12         "GPUs available: {}".format(tf.config.experimental.list_physical_devices("GPU"))
     13     )
     14     if int(tf.__version__[0]) < 2:

AttributeError: module 'tensorflow' has no attribute 'config'

**Comment by timsainb** [comment]
I made an update last night that added in support for tensorflow as a backend, but broke for people with tensorflow < 2.0beta. The bug should be fixed now. 

Let me know and close the issue if so.
