### ISSUE TITLE
Unit of time used in deciding the length of noisy part

### ISSUE THREAD

**Issue by KoushikiNath19** [timsainb/noisereduce#21]
Hi, What time unit are you using in this part of the code?

`noisy_part = data[10000:15000]`

Regards.

**Comment by Tortoise17** [comment]
I am also confuse here. !!

**Comment by huynguyen82** [comment]
The time unit for data[x:y] should be: x/(rate/1000)ms : y/(rate/1000)ms

**Comment by timsainb** [comment]
@huynguyen82 is correct here, the units are samples.
