### ISSUE TITLE
Fix Import Errors

### ISSUE THREAD

**Issue by blaine12100** [timsainb/noisereduce#23]
After installing this library for python 2.7, i found the following issues with file imports.

1) In the __init.py__ section, the first line i.e from noisereduce.noisereduce just needs to be from noisereduce import reduce_noise

2)In the noisereduce.py file the 4th line i.e the from noisereduce.plotting simply needs to be from plotting import plot_reduction_steps.

I cannot create a new branch and push the code for fixing this issue.If you get the time can you please fix these 2 import issues?

Thanks.

**Comment by timsainb** [comment]
Thanks for letting me know. I'm not actively trying to support python2, but if you find the time to fix these issues (before I do) feel free to make a pr and I'll be happy to incorporate the changes. 
Thanks!

**Comment by blaine12100** [comment]
Actually, I have fixed these issues on my local system but I don't know how
can I submit a pull request for the same.

**Comment by timsainb** [comment]
Hi @blaine12100. Maybe this would be a good opportunity to learn! Try following this tutorial here: https://help.github.com/en/articles/creating-a-pull-request-from-a-fork
