### ISSUE TITLE
bug: Masked signal isn't calculated correctly which causes distortion

### ISSUE THREAD

**Issue by uriyapes** [timsainb/noisereduce#28]
If prop_decrease=0 the recovered_signal returned in reduce_noise function should be the same as the input signal to the function. This doesn't happen.
The reason it doesn't happen is because of a bug in mask_signal function. Inline 113 sig_stft_db_masked is calculated and later treated as it only contains the masked real part of the stft. This is wrong since sig_stft_db contains the magnitude of the stft (Real and Imaginary) which means that sig_stft_db_masked cannot contain only the real part.
This bug causes the real part of sig_stft_amp to be too large, which causes some sort of distortion.

**Comment by timsainb** [comment]
Thanks for pointing this out @uriyapes. Do you have a fix for this?

**Comment by uriyapes** [comment]
Your package helped me so I'm happy to help you back.

I used the following patch to calculate sig_stft_amp:
sig_stft_amp = sig_stft * (1 - sig_mask)

I tested it with  prop_decrease=0 and got the same input signal, and for  prop_decrease=1 the recovered signal sounded better.
Notice that I didn't use mask_gain_dB( = np.min(_amp_to_db(np.abs(sig_stft)))) since I didn't fully understand it's purpose.
