### ISSUE TITLE
How can I save the reduced noise in a wav file??

### ISSUE THREAD

**Issue by jcabrerahi** [timsainb/noisereduce#34]
I listen and plot the reduced noise, but how can I save the reduced noise in a wav file??

I save like this:

`librosa.output.write_wav('./prueba/audio_reduce1.wav', reduced_noise, sr)`

But the wav file is noise.

Help me please!

**Comment by abhinashsivan** [comment]
# load data
rate, data = scipy.io.wavfile.read("noisy_audio.wav")
# performing noise reduction on whole part
noisy_part = data
# perform noise reduction
reduced_noise = nr.reduce_noise(audio_clip=data, noise_clip=noisy_part, verbose=False)

scipy.io.wavfile.write("clean_audio.wav", rate, reduced_noise)


this should work

**Comment by abhinashsivan** [comment]
# load data
rate, data = scipy.io.wavfile.read("noisy_audio.wav")
# select section of data that is noise
noisy_part = data
# perform noise reduction
reduced_noise = nr.reduce_noise(audio_clip=data, noise_clip=noisy_part, verbose=False)

#saving the clean audio
scipy.io.wavfile.write("clean_audio.wav", rate, reduced_noise)

**Comment by abhinashsivan** [comment]
# load data
rate, data = scipy.io.wavfile.read("noisy_audio.wav")

# selecting whole file to perform the noise reduction
noisy_part = data

# perform noise reduction 
reduced_noise = nr.reduce_noise(audio_clip=data, noise_clip=noisy_part, verbose=False)

# save the noise removed data as wav 
scipy.io.wavfile.write('clean_audio.wav', rate, reduced_noise)

**Comment by asarsembayev** [comment]
> scipy.io.wavfile.write('clean_audio.wav', rate, reduced_noise)

I have the same issue as @jcabrerahi . I tried `scipy.io.write(), librosa.output.write_wav(), wavfile.write()`. Nothing changes only plain noise. However, I obtained cleaned and good audio and I can listen to it in `IPython.display.Audio(data=reduced_noise, rate=rate)`
Anyone knows what's the problem?

**Comment by timsainb** [comment]
You are probably saving in the wrong format. E.g. saving data in int16 as float32 or vice versa. Try loading the saved data back up in python using scipy.io and take a look at the data.

**Comment by asarsembayev** [comment]
> You are probably saving in the wrong format. E.g. saving data in int16 as float32 or vice versa. Try loading the saved data back up in python using scipy.io and take a look at the data.

Indeed. Thanks a lot @timsainb !
`scipy.io.wavfile.write('1.wav', rate, np.asarray(reduced_noise, dtype=np.int16))` worked for me.
@abhinashsivan , try to follow too.

**Comment by abhinashsivan** [comment]
Sure, Thanks.
