### ISSUE TITLE
module noisereduce.plotting not found

### ISSUE THREAD

**Issue by abhinashsivan** [timsainb/noisereduce#35]
I installed using pip. (pip install noisereduce)

While running the .py file  I'm facing an error " module noisereduce.plotting not found "
![image](https://user-images.githubusercontent.com/37009661/76000764-2b6c3b80-5f2a-11ea-8b92-3b24a7c6e37f.png)

**Comment by timsainb** [comment]
Noisereduce was updated, this should be fixed in the new version
