### ISSUE TITLE
code fails whilst performing STFT on signal "Killed: 9"

### ISSUE THREAD

**Issue by JackSCJackson** [timsainb/noisereduce#39]
Code:

import noisereduce as nr
import scipy.io.wavfile as RE
# load data
rate, data = RE.read("sample.wav")
data = data/1.0
# select section of data that is noise
noisy_part = data[0:37526917]
noisy_part = noisy_part.sum(axis=1) / 2
# perform noise reduction
reduced_noise = nr.reduce_noise(audio_clip=data, noise_clip=noisy_part, verbose=True)
RE.write('clean_audio.wav', rate, reduced_noise)

Code fails during STFT and prints "Killed: 9"

**Comment by timsainb** [comment]
can you reproduce the problem on a google colab notebook

**Comment by JackSCJackson** [comment]
https://colab.research.google.com/drive/1JnQ7rrF0keWfWw1MXf-MWBHtvELj_POX

**Comment by timsainb** [comment]
I meant a notebook that I could run the code and reproduce your error easily.
