### ISSUE TITLE
Difference in behaviour between noise reduce and Audacity noise reduction effect

### ISSUE THREAD

**Issue by joshgreifer** [timsainb/noisereduce#42]
I've trawled through the C++ source for audacity's noise reduction effect,  but I'm still unsure

1.  in what way noisereduce.py differs from it (algorithmically) - and I'm also unsure 

2. how the 'Sensitivity' control in the effect  relates to the std_threshold paramater in noicereduce.py.

Can you explain?

**Comment by timsainb** [comment]
If you have any ideas for adding features like sensitivity let me know. At the moment std_threshold_parameter is just the threshold for how many STDs above the mean power for each frequency channel to consider signal.

**Comment by joshgreifer** [comment]
Hi, thanks for responding!  I'm checking the code more thoroughly, so I closed this ticket until i'd done so - The sensitivity I'm referring to is used in e.g. https://github.com/audacity/audacity/blob/47fa55c4b753f46436c39dcea759f698af9ee7d4/src/effects/NoiseReduction.cpp#L1112  -  The median/casting out outliers approach used there seems to produces better output less prone to chime, as his comment suggests.  If I achieve some improvement I'll link
