### ISSUE TITLE
RAM getting crashed for a 4 second audio

### ISSUE THREAD

**Issue by AhmedBhati** [timsainb/noisereduce#49]
Hi, I have been trying to reduce the background stationary noise from a 4 second audio signal but the RAM crashes on Google Colab.
It gives the user warning as  n_fft=1024 is too small for input signal of length=2 n_fft, y.shape[-1]
The sampling frequency of the audio signal is 44100 Hz, file type is wav file and is a 16 bit file.
I have attached the audio signal here by converting it into mp4 format because github wasn't allowing to upload .wav file.
Thanks

https://user-images.githubusercontent.com/48443838/129436081-980848cd-fd79-4d5f-9dd7-d9ef96910105.mp4

**Comment by timsainb** [comment]
Your error script is saying it things your audio is length 2. You probably need to transpose it, or select one of the two channels.

**Comment by AhmedBhati** [comment]
thanks, it worked on a single channel
