### ISSUE TITLE
How do we compute the residual signal

### ISSUE THREAD

**Issue by sharathadavanne** [timsainb/noisereduce#52]
Hi @timsainb thanks for making the repo public.
I was trying to separate a given audio recording into speech and residual noise in the non-stationary case. I couldn't find a clean way to obtain the residual noise. Any suggestions?
According to the code the denoised version is obtained as `sig_stft_denoised = sig_stft * sig_mask`. I tried to obtain the residual as `sig_stft_residual = sig_stft * (1-sig_mask)` but this doesn't seem to behave as expected since `sig_mask` values are not always bound to `[0, 1]`

**Comment by nuniz** [comment]
Hi,
The signal mask (sig_mask) should always be a value between 0 and 1. It represents the fraction of the signal that is allowed to pass through the filter. Please provide a test case if you have one where this is not the case.

To extract the residual, you need to modify the [factor decrease calculation](https://github.com/timsainb/noisereduce/blob/13c9aacb58221a67a3ac25896a1ad0cce64e9779/noisereduce/torchgate/torchgate.py#L235).
