### ISSUE TITLE
Having problems of calculating the unit of x axis and y axis

### ISSUE THREAD

**Issue by Khhkh** [timsainb/noisereduce#66]
I am a beginner of this project and curious of how to figure the value of the unit of x,y axis。

**Comment by nuniz** [comment]
Hi,
If you are looking at the raw waveform, it is a vector that is sampled at each sample time (1/sampling frequency). Each value represents a number sampled at <number of quantization bits, usually 16, 24, 32, ...>. The maximum value of the waveform is equal to the maximum voltage of the ADC recording.

The WAV format usually normalizes the values between -1 and 1, where 1 represents the maximum value of the quantization. 

A spectrogram graph divides the signal into frames (usually ~24 ms), where each frame goes through an FFT. The graph's x-axis is time or samples, the y-axis is the frequency bins of the FFT, and the color is the intensity (usually the log of the absolute value).

Which plot is more useful depends on the specific task.

Best,
Asaf.
