### ISSUE TITLE
GPU support?

### ISSUE THREAD

**Issue by emhamel** [timsainb/noisereduce#68]
Hello!,

I am trying to use noisereduce's reduce_noise function to clean some audio data.  When I use a GPU (V100), some of the cleaned audio arrays come back as all NaN.  This does not happen when I run the code on CPU.  Any idea of how I might be able to fix this? Thanks!

**Comment by timsainb** [comment]
Does this happen with all of your data or just some? Could you try to reproduce the issue in a colab notebook?

**Comment by emhamel** [comment]
Only with some data, I'll work on making a colab notebook to reproduce the issue, thanks!

**Comment by timsainb** [comment]
Closing since we changed the GPU backend.

**Comment by lzk901372** [comment]
I still face same the issue. Any updates?
