### ISSUE TITLE
[Question] Remove Artifacts Above Certain Frequency?

### ISSUE THREAD

**Issue by zaptrem** [timsainb/noisereduce#78]
Hello, is there a way to filter noise only above a certain frequency? I'm working with an algorithm that sometimes introduces audio banding artifacts only above bin 48 in this mel spectrogram: 
![image](https://user-images.githubusercontent.com/1612230/218829521-aab3942e-4672-433f-8850-442b4ad3c9aa.png)

**Comment by timsainb** [comment]
There isn't but it would be easy to implement - you just need to set the mask outside of the frequency range of interest to zero here:

https://github.com/timsainb/noisereduce/blob/master/noisereduce/noisereduce.py#L438

**Comment by nuniz** [comment]
Hi,
To reduce the noise of certain frequency bands, modify the [gating mask](https://github.com/timsainb/noisereduce/blob/13c9aacb58221a67a3ac25896a1ad0cce64e9779/noisereduce/spectralgate/stationary.py#L117C1-L117C52) before applying it to the signal, always allowing the non-noise reduced time-frequency bins to pass. The spectrogram is not equivalent to the mel spectrogram, but you can calculate the equivalent relevant frequency for each mel band.
