### ISSUE TITLE
LLVM ERROR: Symbol not found: __svml_cosf8_ha

### ISSUE THREAD

**Issue by LucaSoriani1** [timsainb/noisereduce#79]
When i try to run

reduce_noise(y=data, sr=rate, n_std_thresh_stationary=1.5, stationary=True)

I get the error: LLVM ERROR: Symbol not found: __svml_cosf8_ha

**Comment by timsainb** [comment]
When I googled that error it looks like it might have something to do with the version of numpy you have installed

**Comment by LucaSoriani1** [comment]
I tried downgrading both numba and numpy to different versions, but the problem remained
