### ISSUE TITLE
volume reduction after denoising

### ISSUE THREAD

**Issue by ashu5644** [timsainb/noisereduce#86]
Hi @timsainb , I am using noisereduce for noise reduction of large audio files ~1hr. In cleaned version, volume of speech audio is low compared to original audio. I need to use this cleaner output further for transcription use case. Is there any way to restore volume level of speech part to original level.

**Comment by timsainb** [comment]
Hi,

To optimize the sound to the audio relative to the background noise you can play around with parameters like prop_decrease, the threshold , and the sigmoid slope (see the readme.md). If you just want to increase the overall volume in decibels you can use something like pydub. https://stackoverflow.com/questions/13329617/change-the-volume-of-a-wav-file-in-python

**Comment by ashu5644** [comment]
Thank you @timsainb. I will try fine-tuning of parameters.
