### ISSUE TITLE
I have a problem Please help me

### ISSUE THREAD

**Issue by mostafahaggag** [timsainb/noisereduce#9]
Hello! I will tell you my problem and please help me.
I am using Bluetooth headphones which I wear inside of a helmet. There is usually noise when recording any wav file inside of python. I thought about your library as I was thinking about removing the noise from the recorded wave file. The noise is caused by Bluetooth connection and the noise created by the car. I did the following, I recorded a 2-second wav file without any speech. This file mainly used to record the noise in the environment I am sitting in. Then, I recorded another file with me talking in the same environment for 2 seconds.

> `rate, data = read("noise.wav")#the 2 second noise without any speaking
rate2, data2 = read("testing3.wav")#the 2 second noise + me talking
noisy_part = data[:]
reduced_noise = nr.reduce_noise(audio_clip=data, noise_clip=noisy_part, verbose=False)
write("lili.wav", frequency, reduced_noise)#saving the data into a new wav file'

I keep getting this error. I have a deadline tomorrow and I hope you could help me find out the problem in this error. I was wondering if you might have any ideas whether the method I am doing to remove the noise from the 2-second wave file will work or not. If you have any better methods I would be very thankful. I tried using high pass low pass bandwidth mean filter separately but the results are not that promising. It would great if you could give me your advice.
This is  a link to the code  and the files
https://drive.google.com/open?id=1J9abNuhtJpI01pm-LIKFg8zvS2JBR3rK
The setting of the wav file is 
CHUNK = 1024
FORMAT = pyaudio.paInt16
CHANNELS = 1
RATE = 44100
RECORD_SECONDS = 2

File "test.py", line 101, in <module>
    reduced_noise = nr.reduce_noise(audio_clip=data, noise_clip=noisy_part, verbose=False)
  File "/home/mostafahaggag/.local/lib/python3.5/site-packages/noisereduce/noisereduce.py", line 123, in reduce_noise
    noise_stft = _stft(noise_clip, n_fft, hop_length, win_length)
  File "/home/mostafahaggag/.local/lib/python3.5/site-packages/noisereduce/noisereduce.py", line 9, in _stft
    return librosa.stft(y=y, n_fft=n_fft, hop_length=hop_length, win_length=win_length)
  File "/home/mostafahaggag/.local/lib/python3.5/site-packages/librosa/core/spectrum.py", line 161, in stft
    util.valid_audio(y)
  File "/home/mostafahaggag/.local/lib/python3.5/site-packages/librosa/util/utils.py", line 159, in valid_audio
    raise ParameterError('data must be floating-point')
librosa.util.exceptions.ParameterError: data must be floating-point

**Comment by timsainb** [comment]
As the error message says, your data needs to be floating point. Google how
to convert e.g. int16 to float32 wav in Python

**Comment by IbrahimJE** [comment]
data = data/1.0
will convert all your data items to float

**Comment by mostafahaggag** [comment]
Thank you so much
I was checked the example 
`import noisereduce as nr
# load data
rate, data = wavfile.read("mywav.wav")
# select section of data that is noise
noisy_part = data[10000:15000]
# perform noise reduction
reduced_noise = nr.reduce_noise(audio_clip=data, noise_clip=noisy_part, verbose=True)`
I was wondering how to pick the length of the noisy part? should i plot the signal and see which part looks noisier? what am I supposed to do? as mentioned before I am trying to remove noise from the sound wave.
THank you

**Comment by timsainb** [comment]
Yes, plot (or listen to) the data and find a noisy part. The other arguments to play around with are located on the readme.md

```
n_grad_freq (int): how many frequency channels to smooth over with the mask.
n_grad_time (int): how many time channels to smooth over with the mask.
n_fft (int): number audio of frames between STFT columns.
win_length (int): Each frame of audio is windowed by `window()`. The window will be of length `win_length` and then padded with zeros to match `n_fft`..
hop_length (int):number audio of frames between STFT columns.
n_std_thresh (int): how many standard deviations louder than the mean dB of the noise (at each frequency level) to be considered signal
prop_decrease (float): To what extent should you decrease noise (1 = all, 0 = none)
verbose (bool): Whether to plot the steps of the algorithm
```

**Comment by jcabrerahi** [comment]
Hello! How can you save tha reduced noise??

**Comment by ancastillar** [comment]
Hello! How can you save tha reduced noise??

**Comment by Sisalive** [comment]
> Hello! How can you save tha reduced noise??
      

I have tried scipy.io.wavfile.write(outfile,rate,reduced_noise), but it is strange
