### ISSUE TITLE
How to convert an audio stream from PYAudio into the right format to pass to noisereduce?

### ISSUE THREAD

**Issue by DamienDeepgram** [timsainb/noisereduce#92]
I want to apply the noisereduce to a stream of audio

The format in the sample when reading a wav file is `<class 'numpy.ndarray'>`

I am using pyaudio like this
```
audio = pyaudio.PyAudio()
stream = audio.open(
  format=FORMAT,
  channels=CHANNELS,
  rate=SAMPLE_RATE,
  input=True,
  frames_per_buffer=CHUNK,
  stream_callback=mic_callback,
)
```

When I get the audio streaming data it is in the format of `<class 'bytes'>` but noisereduce does not accept that format

```
mic_data = await audio_queue.get()
reduced_noise = nr.reduce_noise(
  y=mic_data, 
  sr=SAMPLE_RATE,
  stationary=True,
  freq_mask_smooth_hz=2000,
  time_mask_smooth_ms=75,
  n_std_thresh_stationary=2
)
```

How can I convert this bytes into a format noisereduce accepts?

I tried `np.tobuffer()` and `np.asarray(chunk)` without any luck

**Comment by DamienDeepgram** [comment]
I was able to make some progress but all the values in the output of the noisereduce are 0

```
mic_data = await audio_queue.get()

numpydata = np.frombuffer(mic_data, np.int16)

reduced_noise = nr.reduce_noise(
  y=mic_data, 
  sr=SAMPLE_RATE,
  stationary=True,
  freq_mask_smooth_hz=2000,
  time_mask_smooth_ms=75,
  n_std_thresh_stationary=2
)
noise_mic_data = reduced_noise.tobytes()
```

**Comment by NickleDave** [comment]
Did you see #44 already?
If not the approach + snippets there might help you

**Comment by DamienDeepgram** [comment]
I figured out the issue actually

I was trying to send smaller chunks of audio 20ms at a time and up to 200ms at a time.

Once I switched to 1sec audio chunks the above code started working for me

**Comment by DamienDeepgram** [comment]
Closing as the above code does the job once frames per buffer and the audio stream was set to 1 seconds (16k in my case since the audio is 16Khz)

**Comment by lonngxiang** [comment]
how to fix？
