### ISSUE TITLE
Minor change in device setting value

### ISSUE THREAD

**Issue by DanTremonti** [timsainb/noisereduce#94]
https://github.com/timsainb/noisereduce/blob/658b8c61368e2cbc9ed1e86bf71ddf61c77852f0/noisereduce/noisereduce.py#L124-L126
Hi, I'm unsure whether the above line could break anything, but perhaps modifying it as
```py
else torch.device("cpu")
```
would be right. What do you think?

**Comment by DanTremonti** [comment]
Probably related - #88

**Comment by timsainb** [comment]
@nuniz does this sound good to you

**Comment by nuniz** [comment]
Hi,
I agree and will address it in the next pull request.
Best, Asaf
