### ISSUE TITLE
Why is torch a mandatory dependency on 3.0.0?

### ISSUE THREAD

**Issue by gallardorafael** [timsainb/noisereduce#96]
Hi,

After updating to 3.0.0, I've found that torch is a mandatory dependency due to the [__init__.py](https://github.com/timsainb/noisereduce/blob/master/noisereduce/spectralgate/__init__.py) file of noisereduce/spectralgate, since it is importing `StreamedTorchGate` from `streamed_torch_gate`.

The complete traceback is the following:
```
  import noisereduce as nr
  File "project/lib/python3.8/site-packages/noisereduce/__init__.py", line 1, in <module>
    from noisereduce.noisereduce import reduce_noise
  File "project/lib/python3.8/site-packages/noisereduce/noisereduce.py", line 1, in <module>
    from noisereduce.spectralgate.stationary import SpectralGateStationary
  File "project/lib/python3.8/site-packages/noisereduce/spectralgate/__init__.py", line 3, in <module>
    from .streamed_torch_gate import StreamedTorchGate
  File "project/lib/python3.8/site-packages/noisereduce/spectralgate/streamed_torch_gate.py", line 1, in <module>
    import torch
ModuleNotFoundError: No module named 'torch'
```
And this happens by just trying to import noisereduce as:
`import noisereduce as nr`

I don't know if this is intentional given that you are trying the spectralgate to be compatible to environments without PyTorch in [noisereduce/noisereduce.py](https://github.com/timsainb/noisereduce/blob/master/noisereduce/noisereduce.py).

This behavior is not present in noisereduce 2.0.1

Thanks.

**Comment by timsainb** [comment]
Good catch. Can you see if this works for you: https://github.com/timsainb/noisereduce/tree/patch-torch-dependency

**Comment by gallardorafael** [comment]
Hi,

3.0.1 (from path-torch-dependency) works like a charm, torch is not mandatory anymore.

Thanks!

**Comment by DaFrenchFrog** [comment]
Sorry, noob question : I still have this issue when installing noisereduce with pip. Is it normal ?

**Comment by gallardorafael** [comment]
@DaFrenchFrog no noob questions. It's better to ask than losing too much time trying to figure it out by yourself. 

The branch where the solution was implemented https://github.com/timsainb/noisereduce/tree/patch-torch-dependency has not been merged into the actual release (which I assume is the one you are getting with pip) 

So I'd recommend to try to pip install from that branch.
