### ISSUE TITLE
type error when trying to run code can anyone help? 

### ISSUE THREAD

**Issue by A3r0Nothin** [timsainb/noisereduce#98]
having trouble getting code to run could I get some help with a solution to this problem? 

import noisereduce as nr
import librosa
import soundfile as sf

def reduce_noise(input_audio_path, output_audio_path, noise_level=0.005, verbose=True):
    # Load audio file
    audio_data, sr = librosa.load(input_audio_path, sr=None, mono=True)

    # Perform noise reduction
    reduced_noise = nr.reduce_noise(audio_clip=audio_data, noise_clip=audio_data, prop_decrease=noise_level)

    # Save the denoised audio
    sf.write(output_audio_path, reduced_noise, sr)

    if verbose:
        print("Denoising complete. Denoised audio saved to:", output_audio_path)

if __name__ == "__main__":
    # Replace 'your_input_audio.wav' and 'denoised_output_audio.wav' with your actual file paths
    input_audio_path = 'Alysha.wav'
    output_audio_path = 'Alysha_denoised.wav'

    # Set the noise level according to your audio characteristics
    noise_level = 0.005

    # Perform noise reduction
    reduce_noise(input_audio_path, output_audio_path, noise_level)

this is the error I get when I run it.

TypeError: reduce_noise() got an unexpected keyword argument 'audio_clip'

thank you for the help.

**Comment by nuniz** [comment]
Hi,
Please ensure that the parameters are provided as follows:

1. audio_clip: The audio clip should be represented by the variable y.
2. noise_clip (optional): The noise clip should be represented by the variable y_noise.
3. sampling_rate: The sampling rate of both the audio clip and the noise clip should be represented by the variable sr.

For more information, please refer to the readme file.
