### ISSUE TITLE
TorchGate init parameter win_length type error

### ISSUE THREAD

**Issue by xiaosong-ai** [timsainb/noisereduce#99]
win_length: bool = None,

should be

        win_length: int = None,

**Comment by nuniz** [comment]
Hi ,
Thanks for reporting this! I actually remembered that we'd already fixed this bug previously. I've implemented that fix in branch 99-torchgate-init-parameter-win_length-type-error, which you can use immediately before the PR is merged.

Best regards,
Asaf

**Comment by xiaosong-ai** [comment]
Actually I have a question. 

I found applying the noise reduce to a file gets good result. But my requirement is for realtime audio stream. I chunk the audio and send clips/chunks to NR or TG. But the effect depends on the size of the audio chunk. If it is too small, the effect is not good. I understand that. Then I use a sliding window for the audio. I always make sure chunk size is equal to the sliding window length by just use last length data (if data is less than window length I return original data). The effect is good if I apply sliding window and tune correct window length. But I found another issue, NR and TG cost too many computing power because they use FFT and torch. If the system has GPU, the performance is OK. If the system has CPU only, even I use separated CPU processor for NR and TG, the performance is still too slow to be usable for realtime audio stream. I think major issue may be that we calculate FFT too many duplicated times when sliding window shifts.

Do you know anyway I can reuse the FFT result? Or does NR has an API for streaming audio with good performance?

Thanks & Regards
Xiaosong

**Comment by xiaosong-ai** [comment]
When I try to set the value freq_mask_smooth_hz and time_mask_smooth_ms to 0, I get following error:

noisereduce/torchgate/torchgate.py", line 94, in _generate_mask_smoothing_filter
    f"freq_mask_smooth_hz needs to be at least {int((self.sr / (self._n_fft / 2)))} Hz"

It looks like “self._n_fft” should be “self.n_fft”.

But anyway, I can’t directly set them to 0.

Regards
Xiaosong

**Comment by nuniz** [comment]
Hi, 
Try running it with None rather than 0.
